BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "meta-calixto-ti"
# Pattern for recipes in this layer
BBFILE_PATTERN_meta-calixto-ti := "^${LAYERDIR}/"
# Layer priority
BBFILE_PRIORITY_meta-calixto-ti = "99"
# Recipes and bbappends
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
# Yocto compatible series
LAYERSERIES_COMPAT_meta-calixto-ti = "kirkstone scarthgap styhead walnascar whinlatter"

